PyCQA/flake8-bugbear

README.rst, bugbear.py, setup.py, tests/b307.py, tests/b901.py, tests/test_bugbear.py
=> Warn against combining yield and return-with-value

bugbear.py, tests/b901.py
Just found this bug while running bugbear against my own code. Really sorry for not checking sooner!
=> Fix bug in B901 check wrt closures

README.rst, bugbear.py, tests/b902.py, tests/test_bugbear.py
=> B902 now deals with metaclasses

.flake8, README.rst, bugbear.py, setup.py, tests/b001.py, tests/b002.py, tests/b004.py, tests/b005.py, tests/b006_b008.py, tests/b301_b302_b305.py, tests/b303_b304.py, tests/b901.py, tests/b903.py, tests/test_bugbear.py
=> Black all the .py files - Like one should

README.rst, bugbear.py
- Also update changes for 19.3.0
- Add in missing 18.8.0 changes into README.md too
Tested via building:
```
python setup.py sdist
python setup.py bdist_wheel
```
=> Move to version to 19.3.0 for release

README.rst
Now the last entry is a link like the other ones.
=> Fix ReST in README.rst

.flake8, .travis.yml, tests/test_bugbear.py
- Fix .flake8 to comply with black
- Fix line number for test_b006_b008
- Upgrade pip + setuptools for CI
Fixes #82
=> Fix failing unittests

README.rst, bugbear.py
- Also fix black link
- Update README.rst
=> Move to version to 19.8.0 for release

.github/workflows/pypi_upload.yml, README.rst, bugbear.py, setup.cfg
- Update changelog
- Add action to upload to PyPI on release creation
=> Move to Version 20.1.0 + add Upload GitHub Action

README.rst
=> Improves README.rst

setup.py
Background info at
https://github.com/pypa/warehouse/pull/7882#issue-412444446
=> Add change log project URL

bugbear.py
=> Add missing call to generic_visit

bugbear.py, tests/b018_classes.py, tests/b018_functions.py, tests/test_bugbear.py
Stops false positive for #208 issue - We need to evaluate if we can be smarter and re-add this detection in future releases.
=> Remove detection of strings in B018

README.rst, bugbear.py
Ok - We've also now moved to `main` branch as it's more correct terminology.
=> Update version + Change Log for 22.3.20 release

tests/b013.py, tests/test_bugbear.py
=> Ignore black formatting for b013 test case

README.rst, bugbear.py
I am but one man who struggles to have time these days ...
=> Update version + Change Log for 22.6.22 release

README.rst, bugbear.py
Making a PR to check my README formatting ...
=> Update version + Change Log for 22.7.1 release

bugbear.py
=> Add missing error code to message for B024

README.rst, bugbear.py, tests/b028.py
This also rewrites the syntax in the tests because it seems like I messed that up the first time!
=> B028: Allow stacklevel to be explicitly assigned as a positional argument

README.rst, bugbear.py, tests/b905_py310.py, tests/test_bugbear.py
=> Add exclusions for B905

tests/test_bugbear.py, tox.ini
- Reenable fuzzing
- Have tox install all deps
=> See if hypo* now work with 3.12

bugbear.py
Ran `autotyping --safe` and fixed the new mypy errors.
=> More types

pyproject.toml
Due to #485 / #486, bugbear now requires at least attrs 22.2.0
=> Bump required attrs version
