PyCQA/flake8-bugbear

- setup.py
This should make it easier to search PyPI for Flake8 plugins and allow people to find bugbear faster.
> Add Flake8 classifier to setup.py

- README.rst
- bugbear.py
- tests/b903.py
- tests/test_bugbear.py
This tests for
```python
class Foo:
def __init__(self, bar, spam, eggs):
self.bar = bar
self.spam = spam
self.eggs = eggs
```
resulting in
> B903 Data class should either be immutable or use \_\_slots__ to save memory. Use collections.namedtuple to generate an immutable class, or enumerate the attributes in a \_\_slot__ declaration in the class to leave attributes mutable.
> Proposed test: b903, data classes should be namedtuples or slots

- README.rst
Previously without the schema, it would have an invalid link, creating a relative link within github.com
Adding the `https://` created the appropriate absolute link.
> Fix pathlib link in readme

- setup.py
As the project only supports Python 3, should document this using ad trove classifier in setup.py.
For a full list of trove classifiers, see:
https://pypi.python.org/pypi?%3Aaction=list_classifiers
> Add trove classifier 'Programming Language :: Python :: 3 :: Only'

- bugbear.py
Even with a default value, this produces warnings from flake8's plugin parameter validation. The plugin is never manually instantiating an instance anywhere, so the current ability to pass it in is unused.
> Avoid adding the visitor as an __init__ parameter (Fixes #39)

- bugbear.py
- tests/b006_b008.py
- tests/test_bugbear.py
Uncommon to see this but these calls are OK as default argument nodes
> Exclude immutable calls like tuple() and frozenset() from B008

- bugbear.py
1. The file does not have executable permission, so the shebang is never
evaluated.
2. The file is not installed as a command line entry point, but as a
flake8 extensions.
3. `bugbear.py` does not have any standalone side effects. It defines a
class, but does not run any code at the top-level. For example,
running::
```
python bugbear.py
```
Has no permanent side effects.
> Remove unused shebang from bugbear.py

- README.rst
- bugbear.py
- tests/b902.py
PyCharm's inspector wants the first arg of metaclass class methods to be called "mcs", it will complain if it's called "metacls" or any of the names Bugbear currently allows. I'd like to be able to satisfy both PyCharm and Bugbear. Since there dosen't appear to be a source of truth for this list of allowed names, I felt it was OK to add this one.
> allow 'mcs' for metaclass classmethod first arg

- README.rst
- bugbear.py
- tests/b011.py
- tests/test_bugbear.py
Do not call `assert False` since `python -O` removes these calls.  Instead
callers should `raise AssertionError()`.
> Introduce B011

- bugbear.py
- tests/b902.py
Add `__class_getitem__` as implicit class method.
This method was introduced by [PEP 560 into Python 3.7](https://www.python.org/dev/peps/pep-0560/).
> add __class_getitem__ as implicit class method

- README.rst
These were only wrapped in single backticks, but double backticks are needed.
> README: fix formatting for identifiers

- bugbear.py
- tests/b901.py
Hey! We are using bugbear wrapped inside a tool which parses flake8 messages for our code. There was a colon after B008, which we found when our parsing didn't look quite right. The colon was also inconsistent with the other flake8 messages... so this is a little PR that removes it.
Thanks! Great plugin!
> Removed a colon from the descriptive message in B008.

- README.rst
- Explain lints are opinionated and not standards
- Explain flake8 plugin design as the other reason
Fixes #92
> Add explanation for not including lints in main lint tools

- README.rst
- bugbear.py
- tests/b012.py
- tests/test_bugbear.py
Context:
Fixes : #99 
The new warning has code B012 and is enabled by default.
Bonus: refactored `check_for_b901()` to just use a recursive loop since I was initially trying to reuse that function, but turned out to be messy.
> Warn about continue/return/break in finally block

- README.rst
> Remove any mention of Python 2 in README

- .travis.yml
- setup.py
- Use official 3.8 release
- Run tests via coverage + show coverage (setuptools has deprecated test option)
- Use black's recursive file finding abilities
Fixes #95
> Cleanup CI + Remove 3.5 Classifiers

- .flake8
- .travis.yml
- setup.cfg
- tests/test_bugbear.py
- Add E998 to be ignored in flake8 config
- Sync setup.cfg with flake8 config
- Have CI to do an editable install so coverage hits the bugbear.py in cwd
> Uncomment some test asserts + Fix

- bugbear.py
- tests/b012.py
- tests/test_bugbear.py
> B012 Fix false positive with continue/break in loops in finally

- README.rst
- bugbear.py
- tests/b001.py
- tests/b013.py
- tests/b014.py
- tests/test_bugbear.py
When using a tuple of exception types in an `except` clause, it's easy for inexperienced Pythonistas to include elements that don't have any function at all.  For example:
```python
try: ...
except (Exception, TypeError): ...	 # TypeError is a subclass of Exception (builtins only)
except (MyError, MyError): ...  	 # Duplicate exception types are useless
except (MyError,): ...  			 # Should use bare name, not tuple
except (MyError, BaseException): ... # Even non-builtins subclass BaseException
```
This PR adds checks for all these cases, recommends the improved version (with `as`-clause if applicable), and thus closes #98.
CC @cooperlees
> Add new checks for `except (...):` clauses

- .travis.yml
- bugbear.py
- setup.py
- tests/b013.py
- tests/test_bugbear.py
CC @cooperlees and @AlexandreYang 
As well as fixing the bug, I've added some fuzz-tests that should catch any similar issues before release next time.  
(in this case they don't, meaning that (a) I need to improve Hypothesmith, and (b) there is no affected code in the standard library or any third-party packages in my dev environment.  Rare bug!)
> Fix error on attributes-of-attributes in `except (...):` clauses

- README.rst
> State an ignore might be needed for optional B9x checks

- bugbear.py
- tests/b009_b010.py
- tests/test_bugbear.py
If an object implements `__getattr__` and/or `__setattr__`, the second parameter to a `getattr()` or `setattr()` call might not be a valid Python identifier (e.g. `getattr(foo, "123abc")`). In this case bugbear should not emit B009/B010, since changing to `foo.123abc` would be a SyntaxError. Update the B009/B010 detection to check using a regex.
Fixes #113.
> Silence B009/B010 for non-identifiers

- bugbear.py
- tests/b009_b010.py
- tests/test_bugbear.py
I wrote an argparse CLI with option named `except` - the code works fine with `getattr(ns, "except")`, but `ns.except` is a SyntaxError.  So this patch makes the linter keyword-aware :smile:
> Don't emit B009/B010 for keywords

- .coveragerc
- .gitignore
- .travis.yml
- DEVELOPMENT.md
- README.rst
- setup.py
- Instruct people how to run our tests
- Add .coveragerc to only show coverage for bugbear.py
- Update setup.py to have a dev extras require to make development installing easier
- Update CI to use new dev extras install
Test:
- Follow my own documentation:
```
cooper-mbp1:flake8-bugbear cooper$ /tmp/tbb/bin/coverage run tests/test_bugbear.py
.......................
----------------------------------------------------------------------
Ran 23 tests in 5.593s
OK
```
> Add Development instructions + dev extra requires

- bugbear.py
- tests/b014.py
- tests/test_bugbear.py
Resolves #110 
Resolves #126
```console
(env) richard-26@ubuntu-laptop:~/programming/flake8-bugbear$ cat test.py
try:
with open("bugbear.py") as f:
lines = f.readlines()
except (OSError, IOError):
pass
(env) richard-26@ubuntu-laptop:~/programming/flake8-bugbear$ flake8 test.py
test.py:4:1: B014 Redundant exception types in `except (OSError, IOError):`.  Write `except OSError:`, which catches exactly the same exceptions.
```
> Support exception aliases properly in B014

- README.rst
- bugbear.py
- tests/b015.py
- tests/test_bugbear.py
For me the main reason to have such check is pytest style asserts, they are quite easy to miss in the middle of the test function
```python
def test_number of objects():
...setup code ...
MyModel.objects.count() == 2   # should be `assert MyModel.objects.count() == 2`
...more asserts...
```
so tests are green and developer thinks he's asserted important results in the test.
Pylint has similar rule *pointless-statement* although it's more advanced but it's a pain to run pylint on tests and not all developers can tolerate false positives from it, so I think it would be a good addition to the flake8-bugbear.
Right now that rule checks only comparisons so maybe error should be: "pointless comparison" or we may try to make the rule more complete by including other cases, eg. uncalled …
> Add B015: pointless statement.

- README.rst
- bugbear.py
- tests/b016.py
- tests/test_bugbear.py
This is invalid and the user likely intended to return instead.
GitHub code search is not great but shows a few instances of this:
https://github.com/search?l=Python&p=1&q=%22raise+False%22&type=Code
> Add check for raising a literal

- bugbear.py
- tests/b001.py
- tests/b901.py
- tests/b950.py
- tests/test_bugbear.py
> Remove check for # noqa comments

- tests/test_bugbear.py
- We sometimes get to slow
- This is probably due to VM resources
Fixes #147
> Add Hypotheses settings to ignore too_slow warning

- README.rst
- bugbear.py
- See https://github.com/PyCQA/flake8-bugbear/issues/149
> B015: prepend "assert" and fix verb tense

- bugbear.py
- tests/b006_b008.py
- tests/test_bugbear.py
This PR addresses issue #154, and make sure float infinity/NaN does not trigger a B008 error.  Some unit tests are added.
I tested this code on Python 3.9, I don't know how to test this on Python 3.7 or below (note that this is needed because the ast
module behavior for constants changed), do you have regressions that check across versions automatically?
> make sure float infinity/NaN does not trigger B008

- bugbear.py
- tests/test_bugbear.py
This is an attempt to fix #153
This is my very first experience with `ast` and I'll admit I don't really know what I'm doing. I added a test based on the issue's description, checked that it failed with the current state of the code base as reported, and applied a minimal patch to make it pass without breaking any other test.
> Hotfix issue 153

- README.rst
- bugbear.py
- tests/b017.py
- tests/test_bugbear.py
```with assertRaises(Exception):``` is basically a "catch 'em all" assert that casts far too broad of a net when it comes to detecting failures in code being tested. Assertions should be testing specific failure cases, not "did Python throw /any/ type of error?", and so the context manager form, or the assertRaisesRegex form are far better to use.
With the implementation of this code, it is possible that someone would write ```with self.assertRaises(Exception) as ex:``` and then never check ```ex```, but linters should then warn about the unused context variable.
W503 had to be ignored because ```test_selfclean_bugbear()``` was upset by the warnings being raised for the syntax in use, despite that syntax being the syntax created by the recommended formatter, black.
This kind of lint check …
> Add B017 - detection for an evil form of assertRaises

- bugbear.py
- tests/b017.py
- tests/test_bugbear.py
- Ensure we ignore nodes with no func
Fixes #164
> Add another hasattr() check to b017 visit

- README.rst
- bugbear.py
- tests/b017.py
- tests/test_bugbear.py
The sample case that broke the assumptions in the code was doing a module.Error type assertRaises. In this case, item_context.args[0] is now a Call object (without an id attr), not a Name object. So, qualify the conditions even more, and add a test case for the sample provided by @DStape.
Should address #164
> Bugfix: Verify the element in item_context.args is of type ast.Name

- tests/b009_b010.py
Fixed a call to "getattr" in "Valid setattr usage".
> [fixed] call method for test

- .flake8
- README.rst
- bugbear.py
- tests/b018.py
- tests/b904.py
- tests/test_bugbear.py
Closes #180, by adding a new check ~~B018~~ B904 to recommend [exception chaining](https://docs.python.org/3/tutorial/errors.html#exception-chaining).  For example,
```python
try:
assert False
except AssertionError:
raise RuntimeError  # B904: Within an except clause, use `raise ... from err` ...
```
This turned out to be remarkably easy to add to the existing code 😁
> Add `B904` - Use `raise ... from err` in `except` clauses

- README.rst
- bugbear.py
- tests/b006_b008.py
- tests/test_bugbear.py
> EHN: also raise B006 for list/dict/set comprehensions

- bugbear.py
- tests/test_bugbear.py
This fixes the crash reported in issue #171. Not sure if this is the correct way to fix this, but at least it doesn't crash.
> Do not crash on call in except statement

- bugbear.py
- tests/b018_classes.py
- tests/b018_functions.py
- tests/test_bugbear.py
Catch also useless expressions on the first node in a body if the node is not a string (docstring).
Thanks to @asottile for the idea.
Part of #201
> Improve B018 further

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- DEVELOPMENT.md
- bugbear.py
- pyproject.toml
- setup.py
- tests/b003.py
- tests/b005.py
- tests/b017.py
- tests/test_bugbear.py
This PR adds a basic pre-commit config. More pre-commit checks and configuration should be discussed.
To run the checks on a PR you have to give https://pre-commit.ci access to the repository. Checks will then run automatically on the next push
Closes: https://github.com/PyCQA/flake8-bugbear/issues/197
> add simple pre-commit config

- README.rst
- bugbear.py
- tests/b014.py
- tests/test_bugbear.py
I am honestly a bit embarrassed by my old code. Let's fix it up with better comments and clearer names :slightly_smiling_face: 
Fixes #178
--- 
FWIW Cooper, I wouldn't mind joining this project as a maintainer. I can't promise much as I'm already busy enough with the projects I'm leading right now, but you _are_ running an one-man show here :)
> B014: catch binascii.Error and ValueError redundancy + cleanup

- README.rst
- bugbear.py
- tests/b008_extended.py
- tests/test_bugbear.py
This PR adds in option to extend the list of immutable calls. Calls to these method as argument defaults no longer raises a `B008` warning.
This is useful when using library like `fastapi` which comes with their own set of immutable calls.
Closes: https://github.com/PyCQA/flake8-bugbear/issues/203
> Add Option to extend the list of immutable calls

- bugbear.py
- tests/b904.py
- tests/test_bugbear.py
Resolves #190. Introduces a simple version of context management, though more detailed analysis might need something a little bit specialized in the future (e.g [stuff like this](https://github.com/isidentical/refactor/blob/1178e9faee21227b5f73f8815724cf9bae048200/refactor/context.py#L165-L177)).
> B904: ensure the raise is in the same context with the except

- .gitignore
- README.rst
- bugbear.py
- tests/b950.py
- tests/test_bugbear.py
Fixes #176 
Allows for the same special cases as E501 for B950
> Allow the same special cases for B950 as E501 (#176)

- setup.cfg
Pure Python 3 packages need not include any configuration for `bdist_wheel`. Currently the wheels on PyPI could look to someone new as if they only support Python 3.6-3.8
- https://pypi.org/project/flake8-bugbear/21.11.29/#files
But CI is in fact testing through 3.10:
https://github.com/PyCQA/flake8-bugbear/blob/2095bdd2293b5567ea1dbeb485cab7da13a2e2fe/.github/workflows/ci.yml#L11
Supported Python versions are enforced through:
https://github.com/PyCQA/flake8-bugbear/blob/2095bdd2293b5567ea1dbeb485cab7da13a2e2fe/setup.py#L42
This change will build proper `*-py3-none-any.whl ` wheels.
> Build universal Python 3 wheels

- bugbear.py
- tests/b018_classes.py
- tests/b018_functions.py
- tests/test_bugbear.py
> Ignore JoinedStr for B018

- .gitignore
- README.rst
- bugbear.py
- tests/b020.py
- tests/test_bugbear.py
A simple typo of the for-loop control variable name `item => items` in loop `[items for items in items]` can lead to an unintended change of the `items` variable.  
Fixes #219
> Add B020 check to find for-loop control variable overiding iter set

- README.rst
- bugbear.py
- tests/b021.py
- tests/test_bugbear.py
Closes #211.
The logic for detecting these f-strings intended as docstrings is fairly simple: Check that the first child of the `FunctionDef`/`ClassDef` is a `JoinedStr`.
I've added a working unit test and ran the pre-commit checks but since this is my first contribution here lmk if I've missed anything 😄
> B021: f-string used as docstring.

- bugbear.py
- setup.cfg
We were already ignoring W503 in `.flake8` since it conflicts with black. This PR cleans up the redundant inline ignores.
Also there was a note saying to keep `.flake8` and `setup.cfg` in sync so I've also updated `setup.cfg` as well 😄 
On a side note, I'm pretty sure we can get rid of `.flake8` since `flake8` can use `setup.cfg` fine when developing. Saves having to keep them in sync.
> Remove redundant W503 inline ignores

- README.rst
- bugbear.py
- tests/b022.py
- tests/test_bugbear.py
Closes #222. 
This covers the case where `contextlib.suppress` is used
```
import contextlib
with contextlib.suppress():  
raise ValueError
```
However, it does not currently cover the case where `suppress` is imported from `contextlib`
```
from contextlib import suppress
with suppress():  
raise ValueError
```
Do you know of any existing flake8 helper functions/methods to tie the `suppress` function node to it's import? 
I don't want to just ignore the one word `suppress` without checking incase it's actually a user defined function.
> B022: No arguments passed to contextlib.suppress

- README.rst
- bugbear.py
Closes #236.
The previous description warned about using lru_cache on `class methods` which is redundant as `methods` belong to a class by definition and leads to confusion with `classmethods` (i.e. methods decorated with `@classmethod`).
﻿
> Clarify B019 description

- bugbear.py
- tests/b020.py
- tests/test_bugbear.py
Closes #235.
Fixes a false positive for B020 where a variable defined in a comprehension is reused in the `for` loop targets.
> B020: Fix comprehension false postives

- bugbear.py
- tests/b006_b008.py
- tests/test_bugbear.py
Closes #242
In #239 I introduced the ability to detect functions at any depth of function default args to prevent things like:
```python
def foo(a=[datetime.now()], b=bar(datetime.now())): ...
```
One thing I overlooked was lambda functions which are slightly different given that their contents act as function body and are therefore only evaluated when the lambda function is called, therefore B008 doesn't apply to these.
```python
from datetime import datetime
import time
def foo(f=lambda x: datetime.now()):
print(f(1))
time.sleep(5)
print(f(1))
foo()
```
prints
```
2022-03-25 11:36:22.999143
2022-03-25 11:36:28.004194
```
Fix is pretty simple, don't check inside lambda functions.
> Fix B008 edge case with lambda functions

- .pre-commit-config.yaml
As part of #239 we updated black version. In the new black version the `--experimental-string-processing` flag has been moved into the `--preview` flag
```
Deprecated: `experimental string processing` has been included in `preview` and deprecated. Use `preview` instead.
```
We can either use the `--preview` flag (has a couple extra new features as well) or just not use any flags. I'd prefer to use the `--preview` flag as we can help improve the newer black features, but easy either way 😄
> Black: replace `--experimental-string-processing` with `--preview`

- bugbear.py
- tests/b009_b010.py
- tests/test_bugbear.py
Closes #122. Allows use of `settatr` within lambda expressions since assignment operators aren't valid in this context.
> Fix B010 lambda false positive

- bugbear.py
- tests/b020.py
> Ignore lambda arguments for B020

- bugbear.py
- tests/test_bugbear.py
resolves #260
this is the minimal fix -- rather than removing the (I believe unneeded) methods I'll let you decide when you want to remove support for old flake8 versions
> don't crash when select / extend_select are None

- README.rst
- bugbear.py
- tests/b024.py
- tests/test_bugbear.py
> Add b024: abstract class with no abstract methods

- README.rst
- bugbear.py
- tests/b025.py
- tests/test_bugbear.py
> Add new check which finds duplicate except clauses

- setup.cfg
- setup.py
This pull request was created using https://pypi.org/project/setuptools-py2cfg plus manual modifications.
https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use
> We recommend users expose as much as possible configuration in a more declarative way via the [pyproject.toml](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) or [setup.cfg](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html), and keep the setup.py minimal with only the dynamic parts (or even omit it completely if applicable).
> Migrate metadata from setup.py to setup.cfg

- .github/workflows/ci.yml
Python 3.11 will be on average 22% faster than Python 3.10 so let’s give it a spin...
https://www.python.org/download/pre-releases
> Add Python 3.11 release candidate 2 to the testing

- README.rst
- bugbear.py
- tests/b024.py
- tests/b027.py
- tests/test_bugbear.py
EDIT: I read through the issues and realized that B024 needs changes, so made this a draft for now.
Implements the second suggested check in #273 
There seems to be some difference in style on ellipsis vs pass, so one might want to restrict the check to only be if the body is docstring and ellipsis.
When reading the docs on abc I also found out that the abstract decorators inside it other than `@abstractmethod` are [deprecated](https://docs.python.org/3/library/abc.html?highlight=abc#abc.abstractclassmethod) so I modified the b024 message to not suggest deprecated decorators.
Modified the b024 test to not trigger b027
Fixes #277, fixes #278 (though see #290), and fixes #280.
> Add B027: empty method in abstract base class with no abstract decorator

- .github/workflows/ci.yml
- DEVELOPMENT.md
- pyproject.toml
- tox.ini
I wrote a basic [tox](https://tox.wiki/en/latest/index.html) config when writing #281 as I was fighting with various version differences and kept failing the CI, and figured other people might find it useful as well.
> add tox config

- bugbear.py
Bugbear is great at catching bugs in our code, but can come across a bit rude when commenting on pull requests 😂  Obviously it's a robot, but we like to encourage polite discourse
> Make bugbear slightly more polite

- bugbear.py
- tests/b023.py
- tests/test_bugbear.py
Picking up from https://github.com/PyCQA/flake8-bugbear/compare/main...Zac-HD:flake8-bugbear:B023-false-alarms
Partially fixes #269 
Fixes some common false alarms where a function is immediately consumed, as an argument to `filter` or `reduce`, as a keyword argument to `key=` and as a return value.
**TODO**: I'm not sure how to handle more complex `return` cases, see the last test cases in `b023.py`.
I'm also not sure if this solution is too generous, it currently marks all direct child nodes to calls to `filter`&`reduce` as safe - but @Zac-HD's [comment](https://github.com/PyCQA/flake8-bugbear/issues/269#issuecomment-1172975488) implies it should maybe be stricter:
> Unfortunately it's more difficult to avoid this false alarm than you might think: for example "lambdas are OK if they're …
> Fix some B023 false alarms

- bugbear.py
- tests/b023.py
- tests/test_bugbear.py
and updated some comments
fixes #269 
@Zac-HD
> also fix map in B023

- bugbear.py
- tests/b027.py
> B027 ignore @overload decorator

- bugbear.py
Thanks so much for this awesome plugin! I just learned about it tonight and tried it out on one of my projects, and it already found a few bugs that `pylint` and standard `flake8` didn't 😍 
While doing that, I saw the following message.
> B015 Result of comparison is not used. This line doesn't doanything. Did you intend to prepend it with assert?
I think `"doanything"` was supposed to be `"do anything"`.
This PR proposes that change.
Thanks for your time and consideration.
> fix typo in unused comparison (B015) message

- README.rst
- bugbear.py
- tests/b027.py
Fixes #304 
it also ignores `@a.b.c.d.overload` in case somebody is writing a custom overload or importing typing in some *very* weird way - but that seems more likely than disaster striking because the check didn't trigger imo. Didn't bother writing a test for that though
> B027 now ignores @[anything].overload to reduce false positives.

- README.rst
- bugbear.py
- tests/b906.py
- tests/test_bugbear.py
Fixes #313 
Also adds `#noqa` to the parts of bugbear's own code that explicitly breaks this.
Opted not to check that it's inside a class, that the parameters are standard, or that `ast` has been imported - which feels fine since it's an optional check.
@Zac-HD
> add B906: visit_ function with no calls to a visit function

- bugbear.py
- tests/b018_modules.py
- tests/test_bugbear.py
Hi!
This PR addresses #267 and enables B018 checks for module-level statements. I'm doing this by visiting the `Module` component in the AST first, and then any children. Let me know if I've missed anything.
Thanks!
> Enable module-level checks for B018

- bugbear.py
- pyproject.toml
- tests/b017.py
- tests/test_bugbear.py
Hi! This PR should solve #169, where calls like `with pytest.raises(Exception):` are not being flagged by B017, even though they are basically the same use case as `with self.assertRaises(Exception)`.
I'm uncertain about the best structure for `tests/b017.py`, and I'm open to suggestions here. For now, I've just added the analogous `pytest.raises` calls for each of the test cases with `assertRaises`.
> Add B017 support for pytest.raises

- .github/workflows/ci.yml
- tox.ini
Seems it works how we need now - Lets see if CI agrees ...
Fixes #300
> Bring back tox-gh-actions

- README.rst
- bugbear.py
- tests/b028.py
- tests/test_bugbear.py
fixes #319 
I decided not to implement 3.7 support at all, expecting it to be dropped soon enough / be rare enough that it's not worth the added code complexity to support it.
3.8 is somewhat of a pain with not having `ast.unparse`, but this implementation should be decent-ish even when there's complex contents of an f-string variable.
This should likely not be merged until edge cases in #319 has been sorted out.
@Zac-HD
> Add B028 - suggest !r for quote-wrapped variables in f-strings

- README.rst
- bugbear.py
- tests/b907.py
- tests/test_bugbear.py
Fixes #329 
Fixes #331 
Fixes #332
For a certain definition of "fixes" at least, the check could perhaps be improved to make it less opinionated and more useful, but silencing lots of unnecessary warnings is the first step regardless.
> Rename B028 to B907, making it optional/opinionated.

- README.rst
- bugbear.py
- tests/b906.py
> B906: ignore functions whose _fields attribute can't contain ast.AST subnodes

- README.rst
- bugbear.py
- tests/b017.py
- tests/test_bugbear.py
Fix https://github.com/PyCQA/flake8-bugbear/issues/334 .
Also add more tests for when we should and shouldn't emit B017.
In particular we should check ``assertRaises`` and ``pytest.raises`` calls outside of with statements.
> B017: don't warn when ``pytest.raises()`` has a ``match`` argument

- README.rst
- bugbear.py
- tests/b024.py
- tests/test_bugbear.py
Fix another case in #278 - so now it won't warn on empty classes or any class without methods, esp since the fix proposed in the error message (consider adding `@abstractmethod`) is not useful in that case.
@Zac-HD @mikhail-melnik
> B024: don't warn on classes without methods

- README.rst
- bugbear.py
- tests/b906.py
Hi, thanks for flake8-bugbear! I'm a maintainer of [the flake8-pyi plugin](https://github.com/PyCQA/flake8-pyi) for flake8, and I'd love to switch on B906 for our codebase, as I think it's a great idea for a flake8-bugbear check. Unfortunately, however, there's still a false-positive if I switch B906 on over at flake8-pyi, even with the latest release (which includes #335).
The false positive is emitted due to the fact that we have [a `visit_Str` method](https://github.com/PyCQA/flake8-pyi/blob/4778623da8494978dceaec54b0597eea050742ed/pyi.py#L985-L997) in our `ast.NodeVisitor` subclass. `ast.Str` has been deprecated since 3.8, but it's necessary for us to define a `visit_Str` method nonetheless in order to maintain backwards compatibility with Python 3.7.
`ast.Str` nodes have a non-empty …
> B906: Add `visit_Bytes`, `visit_Num` and `visit_Str` to the list of ignored `visit_*` functions

- README.rst
- bugbear.py
- tests/b016.py
- tests/test_bugbear.py
Warns when raising f-strings which I think matches the check's current description.
> B016: Warn when raising f-strings

- README.rst
- bugbear.py
- tests/b028.py
- tests/test_bugbear.py
This PR adds a lint which checks for an explicitly defined `stacklevel` keyword argument on the `warn` method from the `warnings` module. If `stacklevel` is not explicitly defined, this lint triggers. See #299 for more information.
I am new to this project and ASTs in general, so any feedback is appreciated! Specifically I don't know whether this should be `B028` or `B029`, as `B028` was used before by `B907`.
Closes #299
> Add a lint checking for warnings.warn stacklevel argument

- README.rst
- bugbear.py
- tests/b001.py
- tests/b029.py
- tests/test_bugbear.py
This splits the part of B001's lint which checked for using `except` with an empty tuple, and moves it into a new lint, B029. As suggested by the comments in #282. Closes #282.
> Split B001 into B029 for empty tuple exception handling

- README.rst
- bugbear.py
- tests/b029.py
- tests/test_bugbear.py
Fixes #345.
This introduces a new bugbear check against things like `except call():` or `except 1:`. This could be legitimate code (if you have a function that returns an exception class), but I'm not sure that's something that would ever come up in practice.
bugbear would previously crash on any except handler that is not a Tuple, Name, Attribute, or Call.
> Introduce B030; fix crash on weird except handlers

- README.rst
- bugbear.py
- tests/b031.py
- tests/test_bugbear.py
I ran into a somewhat subtle bug by accidentally iterating over the result of `itertools.groupby()` twice:
```python
from itertools import groupby
items = [
('lettuce', 'greens'),
('tomatoes', 'greens'),
('chicken breast', 'meats & fish'),
]
for _section, section_items in groupby(items, key=lambda p: p[1]):
for shopper in ['Jane', 'Joe']:
collect_shop_items(shopper, section_items) # "Joe" won't get any items
```
I've written B031 ([since there's a PR open for B030](https://github.com/PyCQA/flake8-bugbear/pull/346)) to detect these types of erroneous usages.
There are likely other functions in `itertools` that return generators and should potentially be covered by this check.
Also, the check is fairly rudimentary. It only works if the `groupby()` is used in a loop and unpacked directly …
> Add B031: Warn when using `groupby()` result multiple times

- README.rst
- bugbear.py
- tests/b032.py
- tests/test_bugbear.py
This lint checks for possibly mistakenly using `:` (for type annotations) instead of `=` (for assigning).
Closes #312.
> B032: Possible unintentional type annotations instead of assignments

- README.rst
Adds a few missing entries to the 23.2.13 release notes.
> Update release notes for 23.2.13

- README.rst
- bugbear.py
hi! it looks like there's a typo in the message and changelog entry for the new B029.
> Fix B029 typo

- README.rst
- bugbear.py
- tests/b030.py
Fixes #352.
I allow calls in addition to splats because a real-world false positive was reported
and buggy code doesn't seem common enough to merit an on-by-default error.
> B030: allow splats and calls

- README.rst
- bugbear.py
- tests/b005.py
This PR changes B005 so that it does not flag when the `strip()` method is used on an imported module such as this:
```python
import test
test.strip("test")
```
I'm not entirely sure if `BugBearVisitor` is the correct place to define `_b005_imports` so please let me know if there's a better place.
This closes #297, but we might want to open a new issue for the configuration of excluded methods, if we want to add that as well.
> B005: Do not flag on imported modules

- tests/b031.py
Change the docstring to the correct code. Change the line numbers that are expected to trigger the warning code.
> Fix typos in docstring

- bugbear.py
- tests/b030.py
- tests/test_bugbear.py
I was working in ruff implementing B030 when I noticed that the test case for the warning didn't look right. It may be that another rule catches this issue, but it made sense to me that B030 would catch it as well.
```python
try:
raise ValueError()
except (ValueError, (RuntimeError, (KeyError, TypeError))):
pass
```
This code causes an exception, `TypeError: catching classes that do not inherit from BaseException is not allowed`, because the inner tuple isn't expanded out automatically. It passes, however, if those tuples are starred:
```python
try:
raise ValueError()
except (ValueError, *(RuntimeError, *(KeyError, TypeError))):
pass
```
The wording for B030 makes it sound like this is the exact error it's meant to catch, so I updated the `_flatten_excepthandler` method to be more …
> Fix bug in b030

- README.rst
- bugbear.py
- tests/b950.py
- tests/test_bugbear.py
Implements #162 
`noqa` and `type: ignore` comments won't be taken into account when checking lines.
In my proposal I use a regular expression, to remove and thus ignore the comments mentioned in the issue.
> B950: Ignores 'noqa' and 'type: ignore' comments (#162)

- .github/workflows/ci.yml
- DEVELOPMENT.md
- pyproject.toml
- tox.ini
Tracking issue: #365
Updates CI to remove 3.7 runs and updates project metadata from 3.7 to 3.8.
Will be needed for CI to run on #366
> (3.8) Update CI and metadata

- bugbear.py
Tracking issue: #365
See python/cpython#77073:
> Num -- for int, float and complex
Str -- for str
Bytes -- for bytes
Ellipsis -- for Ellipsis
NameConstant -- for True, False and None
This looks a bit messy in places but I don't think a helper function would provide that much improved readability (it'd effectively just be re-implementing the deprecation's, which we don't want), and we only use this in a relatively small portion of the code base.
I've just replaced the deprecated literals with their actual meanings, I'm not too sure whether we now want to change some (for example ast.Num checks for int, float and complex but we might only want to check for int).
> (3.8) Replace deprecated ast literals

- bugbear.py
- pyproject.toml
- tests/test_bugbear.py
- tox.ini
Tracking issue: #365
Some minor changes:
- Changes in `bugbear.py` and `test_bugbear.py` from running `pyupgrade --py38-plus` against them (I left the individual test files, not sure if we want to change those)
- A change to `pyproject.toml` setting `requires-python` to `>=3.8.1` instead of `>=3.8` to match flake8
- A change I missed in `tox.ini` on #367
Should we also change the `flake8` dependency requirement from `>=3.0.0` to `>=6.0.0`?
> (3.8) Minor tweaks

- README.rst
- bugbear.py
- tests/b030.py
> Fix crash on unusual except handlers

- bugbear.py
- tests/test_bugbear.py
Tracking issue: #365
Removes outdated `sys.version_info` checks which we don't need with our minimum Python version of 3.8.1.
> (3.8) Remove outdated sys.version_info checks

- README.rst
- bugbear.py
- tests/b033.py
- tests/test_bugbear.py
This checks for duplicate items in sets when using the `{}` syntax.
Adds a part of #371.
> Add B033: Duplicate items in sets

- bugbear.py
- tests/b033.py
- tests/test_bugbear.py
- Include the repr() of the duplicate item in the error
- Point the error directly at the duplicate item
Fixes #384
> Improve B033 (duplicate set items)

- MANIFEST.in
close https://github.com/PyCQA/flake8-bugbear/issues/383
This PR adds `tox.ini` in `MANIFEST.in` for downstream testing.
> add `tox.ini` in `sdist`

- bugbear.py
The `.s` attribute on `ast.Constant` nodes is an alias to the `.value` attribute. The `.s` alias has been deprecated since Python 3.8, and causes a DeprecationWarning to be emitted on Python 3.12
> Remove use of the deprecated `ast.Constant.s` attribute

- bugbear.py
Running flake8 (with flake8-bugbear installed) using Python 3.12 on a file containing this...
```py
class Foo:
def visit_NameConstant(self):
...
```
...will cause this DeprecationWarning to be emitted:
```pytb
flake8-bugbear\bugbear.py:1185: DeprecationWarning: ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead
class_type = getattr(ast, class_name, None)
```
This is because of this line here -- doing `getattr(ast, "Bytes", None)` causes a DeprecationWarning to be emitted on Python 3.12:
https://github.com/PyCQA/flake8-bugbear/blob/2763a13e6d415d5a2cbda51d126f601ae8215480/bugbear.py#L1185
I think the simplest thing here is just to catch and silence any deprecation warnings that might arise as a result of this `getattr()` call. (An alternative …
> Avoid another source of deprecation warnings on py312

- README.rst
- bugbear.py
- tests/b907.py
- tests/test_bugbear.py
Fixes #393. On py312, f-strings parse differently and `ast.JoinedStr` nodes have proper column numbers.
> B907: fix crash and test failures on py312

- README.rst
- bugbear.py
- tests/b034.py
- tests/test_bugbear.py
> Add B034: re.sub/subn/split must pass flags/count/maxsplit as keyword arguments

- .github/workflows/pypi_upload.yml
Closes #390 
Not sure if you wanted to do this yourself, but it's a relatively small change.
FWIW, I ran the workflow locally with `act` and it seemed fine
Cheers :)
> Use pypa/build to build the package

- bugbear.py
Noticed this failing in #405. I don't really understand why it's defined both as a class member and a property, but removing it has no effect as far as I can tell. I think this only fails on 3.12 and as such might be unintended upstream.
> fix name collision for node_stack on python 3.12

- bugbear.py
- tests/b017.py
- tests/test_bugbear.py
Logic for check B017 has been updated to check for cases where `with raises()` is used when `raises` is imported using an `ast.ImportFrom` node (that is, `from pytest import raises`) rather than an `ast.Import` node, which the current logic handles.
This has included some updates for check B005 to ensure `ast.ImportFrom` nodes are added to the "imports" set maintained in the `BugBearVisitor` class.
Tests have been updated to check that this code pattern is now flagged with B017 and tox tests have passed for Python 3.11 (which is what I have installed).
Fixes #418.
> #418: Modify B017 to no longer have a false negative when raises() is imported directly from pytest

- bugbear.py
- tests/b024.py
I faced a false positive when deriving my metaclass from ABCMeta, which should be fixed with this commit. I also added EnumMeta to this list, because it was the only other public metaclass in the standard library.
> B902: Add exceptions for standard library metaclasses

- .pre-commit-config.yaml
- pyproject.toml
Fix to prevent pre-commit ci autoupdate from breaking tests by reformatting test-code and changing line nums. Example: https://github.com/PyCQA/flake8-bugbear/pull/422/files
> update black version, and exclude the tests/b*** files from formatting checks so they don't break tests

- .pre-commit-config.yaml
For https://github.com/PyCQA/flake8-bugbear/issues/412
Just adds basic flake8 +bugbear check to pre-commit config
> add flake8 w/ bugbear to pre-commit config

- bugbear.py
- tests/b035.py
> B035: Fix false positive when named expressions are used (#429)

- .github/workflows/flake8_py_version_check.yml
- scripts/flake8_py_version_check.py
from https://github.com/PyCQA/flake8-bugbear/issues/365
Made a quick standalone python script. Uses curl (so no need to pip install requests or anything else) to get pypy json info for flake8. Grabs the `requires-python = ...` line from pyproject.toml and compares the two, will throw an error if they don't match. 
Note - chose to get bugbear version from pyproject.toml rather than fetching bugbear json because then the test would fail until a bugbear update was uploaded to pypi.
Not sure about naming or folder placement - just stuck it in a `scripts` folder.
Testing:
Made it run on push, and changed the python version in pyproject.toml to see it fail. [Sample error output](https://github.com/r-downing/flake8-bugbear/actions/runs/7041812391/job/19164955564)
<details><summary>error …
> add flake8 python version check script and CI check

- bugbear.py
- tests/test_bugbear.py
Had another idea for an enhancement to the B018 warning, which might make things clearer, especially for the case of tuples. This adds the AST class name to the output. 
test file:
before and after:
> add classname to b018 useless-expression output

- bugbear.py
- tests/b018_nested.py
- tests/test_bugbear.py
The B018 useless-statement checker was only running at the top level of modules, classes, and functions. This meant that it wouldn't detect things inside any nested blocks - e.g. `if`, `for`, `while`, `try`, etc. Did a minor refactor to make the checker run during the basic visit function so it hits things in all scopes.
Example. See added test file for more
```python
[1, 2, 3]  # useless list - would catch this
if x:
[1, 2, 3]  # useless list - would not catch this
```
> B018 to detect useless-statements at all levels

- README.rst
- bugbear.py
- tests/b001.py
- tests/b014.py
- tests/b036.py
- tests/test_bugbear.py
Started implementing this new check per https://github.com/PyCQA/flake8-bugbear/issues/174
Currently just looking for `BaseException` - I figured `Exception` should maybe be a separate, optional one.
It only checks for re-raises at the top-level of the except. I thought maybe checking all branches of of a complex `except` block to see they all re-raise might be overkill - WDYT?
This does contradict the advice (and failing test-cases) of B001:
> Do not use bare `except:`, it also catches unexpected events like memory errors, interrupts, system exit, and so on.  Prefer `except Exception:`.  If you're sure what you're doing, be explicit and write `except BaseException:`.Flake8(B001)
So those would also need to be updated, and should probably change that wording - what do you think should be …
> Implement B036 check for `except BaseException` without re-raising

- bugbear.py
- tests/b017.py
- tests/test_bugbear.py
on the subject of `BaseException` I thought it might make sense for this `assertRaises` check to apply to that as well
> make B017 also apply to BaseException

- README.rst
- bugbear.py
- tests/b037.py
- tests/test_bugbear.py
Implement check for ``return <value>``, ``yield``, ``yield <value>``, or ``yield from <value>`` in class ``__init__()`` method. No values should be returned or yielded, only bare ``return``s are ok.
These would be runtime errors, if and when these statements are reached.
This does trigger on `return None` which is equivalent to `return`, but kind of confusing and pointless to write in a function that shouldn't return anything.
> Implement B037 check for yielding or returning values in __init__()

- bugbear.py
- tests/b038.py
- tests/test_bugbear.py
The unused code would introduce a bug when used, thus I believe it's better to remove it.
Essentially, it would've flagged _any_ `del` statement within a loop, without check for the name. 
However, because the `B038Checker` visits `Del` nodes, and doesn't call `generic_visit` from there, we'll never reach a `Name` node that has the `ctx == Del`.
I've added a test case, just to make sure :slightly_smiling_face:
> refactor(b038): Cleanup unused code in B038Checker

- README.rst
- bugbear.py
- tests/b036.py
- tests/test_bugbear.py
> Fix crash on raise with non-Name value

- bugbear.py
- tests/b038.py
- tests/test_bugbear.py
Previous implementation produced false positives.
This fixes those and adds some more tests.
Fixes #451 
@cooperlees this fixes the bugs described in the issue - There are some more mutating functions (like a ~`dict.popitem()`~ - ok that was an easy one, but `=` and `*=` and `+=` are still left to do) that I won't have time to add today. 
That said, this will only cause false negatives, so I figured I'd push this and create the PR so you can release a fix for the FPs.
> fix(b038): Restrict rule to mutating functions only

- DEVELOPMENT.md
- README.rst
- bugbear.py
This removes methods named `validator` and `root_validator` from the B902 check
Fixes https://github.com/PyCQA/flake8-bugbear/issues/413
Removes false positives for common cases, like using attrs validators
ran `tox` and all tests are passing
> Remove decorators named validator and root_validator from B902 checks

- .github/workflows/ci.yml
- README.rst
- bugbear.py
- tests/b039.py
- tests/test_bugbear.py
- tox.ini
fixes #475
Not the prettiest extension of `FunctionDefDefaultsVisitor`, and left e.g. `B006.mutable_literals` as bound to `B006` and the naming of `b008_extend_immutable_calls`. I'll fix those later unless we want to reuse B006/B008 for `ContextVar`s, or maybe just a couple comments saying that B039 also uses them.
Also adding 3.13 to CI to check for any problems there
> Contextvar mutable or call default

- README.rst
- bugbear.py
- tests/b040.py
- tests/test_bugbear.py
Fixes #474 
There's some alternatives when it comes to the scope of this check, namely whether these two should be caught
```python
def foo():
my_exc = ValueError()
my_exc.add_note("I want to use this variable")
```
I.e. arbitrary exception created anywhere, that appears to only be used for having a note added. This one gets tricky as its complexity approaches that of a type checker, which usually handles unused variables. If we assume that only exceptions will ever have a method called `add_note` we can sidestep trying to do any type inference.
Though this would hit false alarms with stuff like
```python
def my_add_note(e: Exception) -> None:
e.add_note("foo")
```
so it probably isn't worth it.
```python
try:
...
except:
f = ValueError()
f.add_note("")
```
This is essentially the same as …
> add b040: exception with note added not reraised or used

- bugbear.py
- tox.ini
This is minimal for now (didn't add any annotations, didn't turn on strict mode),
just so we can get started. In later PRs I can add more strictness.
Issue #478
> Set up mypy

- bugbear.py
- tests/b901.py
- tests/test_bugbear.py
> Do not trigger B901 with explicit Generator return type

- README.rst
- bugbear.py
- tests/b910.py
- tests/test_bugbear.py
Implementing #323.
I'm not sure if the number B910 is OK, but it's just the next available number (not counting B950).
> Added new check B910 to suggest using Counter() instead of defaultdict(int)

- bugbear.py
Background: https://www.attrs.org/en/stable/changelog.html#deprecations
Closes #485
> Replace hash with unsafe_hash

- .github/workflows/ci.yml
- README.rst
- bugbear.py
- tests/b024.py
- tests/test_bugbear.py
fixes #471 
also 3.13 no longer requires -dev
> b024 no longer treats assigned class vars as abstract

- README.rst
- bugbear.py
- tests/b911_py313.py
- tests/test_bugbear.py
Checks calls to `itertools.batched` and `batch` similar to the implementation of B031.
Closes #498
> Add B911: itertools.batched without strict=

- README.rst
- bugbear.py
- tests/b012_py311.py
- tests/b013_py311.py
- tests/b014_py311.py
- tests/b025_py311.py
- tests/b029_py311.py
- tests/b030_py311.py
- tests/b036_py311.py
- tests/b904_py311.py
- tests/test_bugbear.py
This PR creates a `visit_TryStar` that mostly just calls `visit_Try`, enabling B012 & B025 to work with `try/except*`
Because `ExceptHandler` is also used for `TryStar`, we already have support for free for B014, B029, B030, B036 and B904.
I opted to add tests for them anyway, but it did end up with a somewhat silly amount of added tests - most of which are just pure copy-paste's of their original test files. Another option is writing a single `except_star.py` file that tests all of them, or writing a transformer test that goes through the original files, does a search+replace for `except`->`except*`, and then tests them on the fly. Though the latter option would also involve some rejigging to get the expected errors shared from the original `test_bxxx` functions.
Another case for #419 …
> add except* support to B012&B025

- README.rst
This will allow us to link to them directly.
Using the syntax from https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#use-a-custom-anchor
Example: https://github.com/jtojnar/flake8-bugbear/tree/readme-anchors#user-content-b950
> README: Add anchors for rules and config options

- README.rst
- bugbear.py
- tests/b028.py
> Ignore B028 if skip_file_prefixes is used

- .github/workflows/ci.yml
- README.rst
- pyproject.toml
- CI failed as we'd hoped and it's time to move to >= 3.9 cpython to match flake8
- Here we update all configuration and metadata etc. etc.
This fixes "flake8_py_version_check" CI failing like: https://github.com/PyCQA/flake8-bugbear/actions/runs/14150950748/job/39644039034
> Move project to >= 3.9

- bugbear.py
- tox.ini
the `partial` approach didn't pass typing anymore, though I didn't dig terribly deep into why that might be the case, I simply replaced it with a factory class.
testing 3.14 is blocked by hypothesmith->libcst->PyO3 https://github.com/PyO3/pyo3/issues/5107
> drop 3.8, unpin mypy dep in tox, fix typing errors, add some type hints

- bugbear.py
- tests/eval_files/b042.py
> add B042: exception class with no, or malformed, super().__init__()
